services:
  - type: web
    name: todolist-dhlt
    env: static
    buildCommand: npm ci --legacy-peer-deps && PUBLIC_URL=/ npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://todolist-dhlt-gc0d.onrender.com
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: /