name: Commit Information Display

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  commit-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    - name: Display Commit Information
      run: |
        echo "📋 COMMIT INFORMATION"
        echo "===================="
        echo "🔧 Commit SHA: ${{ github.sha }}"
        echo "📝 Message: ${{ github.event.head_commit.message }}"
        echo "👤 Author: ${{ github.event.head_commit.author.name }}"
        echo "📧 Email: ${{ github.event.head_commit.author.email }}"
        echo "🕒 Timestamp: ${{ github.event.head_commit.timestamp }}"
        echo "🌿 Branch: ${{ github.ref_name }}"
        echo "📁 Repository: ${{ github.repository }}"
        echo ""
        echo "📊 CHANGES"
        echo "=========="
        echo "Modified files:"
        git diff --name-only HEAD~1 HEAD || echo "No previous commit found"
        echo ""
        echo "📈 Stats:"
        git diff --stat HEAD~1 HEAD || echo "No previous commit found"
        
    - name: Files Changed
      run: |
        echo "📂 DETAILED CHANGES"
        echo "==================="
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          git diff --name-status HEAD~1 HEAD
        else
          echo "Initial commit - all files are new"
        fi
        
    - name: Deployment Status
      run: |
        echo ""
        echo "🚀 DEPLOYMENT STATUS"
        echo "===================="
        echo "✅ GitHub Pages: https://aebonlee.github.io/ToDoList"
        echo "⏳ Render (Frontend): https://todolist-dhlt.onrender.com"
        echo "⏳ Render (Backend): https://todolist-dhlt-gc0d.onrender.com"
        echo ""
        echo "📝 Next Steps:"
        echo "1. Monitor Render deployment"
        echo "2. Check build logs if deployment fails"
        echo "3. Verify environment variables in Render dashboard"